In [1]:
import numpy as np


In [7]:
a = np.array([[1,2,3]])
b = np.array([[1],[2],[3]])
c = np.array([1,2,3])

In [8]:
a@b #[[1,2,3]] * [[1],[2],[3]] , two 2d array dot => 2d scalar 

array([[14]])

In [9]:
b@a #[[1],[2],[3]] * [[1,2,3]] , two 2d array dot => 2d Matrix

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [10]:
c@c # [1,2,3] * [1,2,3] , two 1d array dot => scalar

14

In [11]:
a@c # [[1,2,3]] * [1,2,3] , one 2d array dot one 1d array => 1d scalar

array([14])

In [12]:
b@c #[[1],[2],[3]] * [1,2,3] one 2d array dot one 1d array => Error (it seems that the 1d array [1,2,3] can be regarded as row or column vector ? )

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [19]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


In [20]:
A[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])